# Generated by Django 5.0.7 on 2024-07-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_verification_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referree',
            new_name='referee',
        ),
    ]
